config/routes.rb
Rails.application.routes.draw do
  #get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "count/:id", to: "pages#count", as: "group"
  put "groups/:id/next", to: "groups#next", as: "next"
  put "groups/:id/reset", to: "groups#reset", as: "reset"
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :segments, dependent: :destroy

  def value
    groupval = ""
    self.segments.order(position: :asc).each do |segment|
      if segment.date?
        segment.format.each_char do |character|
          groupval.concat(segment.value.to_date.strftime("%#{character}"))
        end
      else
        groupval.concat(segment.value)
      end
    end
    return groupval
  end
end

app/models/segment.rb
class Segment < ApplicationRecord
  belongs_to :group, counter_cache: true

  after_initialize :set_default_date

  enum category: [:alpha, :date]
  enum behavior: [:system, :correlative, :constant]
  enum reset: [:day, :month, :year, :never]

  def reset_value
    self.update(value: self.base_value)
  end

  private

  def set_default_date
    self.date = Time.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group

  def next
    now = Time.now.to_date

    next_group = NextGroupsService.call(@group, now)

    if !next_group.success?
      flash[:alert] = next_group.errors.first[1]
    end

    redirect_to @group
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @group = Group.all
  end

  def count
    @group = Group.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_alerts.html.erb
<% if alert %>
    <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContadorGrupos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/alerts' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/count.html.erb
<div class="container">
  <br>
  <h3><%= "Valor del contador #{@group.name}"%></h3>
  <br>
  <h5>
    <%= @group.value %>
  </h5>
  <br>
  <%= button_to "Siguiente", next_path(@group), method: :put %>
  <br>
  <%= link_to "Volver al menú", root_path %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <br>
  <h1>Contadores</h1>
  <% Group.all.each do |group| %>
    <hr>
    <%= "#{group.name}: #{group.value}" %>
    <br>
    <%=  link_to "Ver contador" , group %>
    <br>
  <% end %>
</div>